name = "RemoteHPC"
uuid = "c4f2a1c4-7655-40d8-82ee-c6ae0a8b7409"
authors = ["louisponet <louisponet@gmail.com>"]
version = "0.3.17"

[deps]
BinaryTraits = "190e46ec-f771-4705-b939-984896f7be0e"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
OpenSSH_jll = "9bd350c2-7e96-507f-8002-3f2e150b4e1b"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
SwaggerMarkdown = "1b6eb727-ad4b-44eb-9669-b9596a6e760f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
BinaryTraits = "0.7.0"
DataStructures = "0.18.13"
HTTP = "1.6.2"
JSON3 = "1.12.0"
LoggingExtras = "1.0.0"
OpenSSH_jll = "8.1"
Oxygen = "^1.1.4"
ProgressMeter = "1.7.2"
SnoopPrecompile = "^1"
StructTypes = "^1"
SwaggerMarkdown = "^0.2.1"
ThreadPools = "^2"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
